version: '3'
services:
  mysql:
    # restart: always
    image: mysql:5.7.33
    container_name: mysql
    volumes:
      - /apps/mysql/datadir:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/my.cnf
      # - ./static/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      # - "MYSQL_DATABASE=yourdbname"
    ports:
      - 3306:3306
    expose:
      - "3306"

  worldserver:
    image: trinity:env
    container_name: worldserver
    volumes:
      - .:/trinity/
    ports:
      - 3724:3724
      - 8085:8085
    expose:
      - "3724"
      - "8085"
    tty: true
    depends_on:
      - mysql
      
  register:
    image: trinity:reg
    container_name: register
    ports:
      - 80:80
    expose:
      - "80"
    depends_on:
      - mysql