FROM ubuntu:22.04

RUN apt update -y && apt upgrade -y

RUN apt install software-properties-common -y && \
    add-apt-repository ppa:ondrej/php -y && \
    apt update -y

RUN apt install php7.4 php7.4-fpm php7.4-gmp php7.4-gd php7.4-soap php7.4-mbstring php7.4-mysql -y

RUN apt install nginx -y

COPY conf/nginx/default /etc/nginx/sites-available/default

COPY register/. /var/www/html/.

CMD service php7.4-fpm start && service nginx start && tail -F /var/log/nginx/error.log



